import { readFile, writeFile, mkdir, cp } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { pages } from '../src/pages.mjs';

const root = fileURLToPath(new URL('../', import.meta.url));
const config = JSON.parse(await readFile(join(root, 'site.config.json'), 'utf8'));
const preview = process.argv.includes('--preview');
let configured = process.env.SITE_BASE_URL || config.baseUrl;
if (preview) configured = process.env.PREVIEW_BASE_URL || 'http://localhost:4173/';
if (!configured) throw new Error('Production base URL is not configured. Set SITE_BASE_URL to the real HTTPS site URL, or use npm run preview:build for local work.');
const base = new URL(configured);
if ((!preview && base.protocol !== 'https:') || base.search || base.hash || base.username || base.password) throw new Error('Use a clean HTTPS production base URL, including the repository subpath.');
if (!base.pathname.endsWith('/')) base.pathname += '/';
const out = resolve(root, process.env.BUILD_OUT || 'dist');
if (!out.startsWith(root) || out === resolve(root)) throw new Error('Build output must be a subdirectory of this project.');
await mkdir(join(out, 'assets'), { recursive: true });
await cp(join(root, 'src/assets'), join(out, 'assets'), { recursive: true });
for (const name of ['styles.css', 'app.js', 'calculations.js']) await cp(join(root, 'src', name), join(out, 'assets', name));
const esc = value => String(value).replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
const url = slug => new URL(slug, base).href;
const icon = (name, label, id, extra = '') => `<button type="button" id="${id}" class="icon-button" aria-label="${label}" title="${label}" ${extra}><img src="assets/${name}.svg" width="18" height="18" alt=""></button>`;
const field = (id, label, value) => `<div class="field" id="field-${id}"><label for="${id}">${label}</label><div class="input-wrap"><input id="${id}" name="${id}" type="number" step="any" inputmode="decimal" value="${value}" aria-describedby="error"><span class="unit-suffix">m</span></div></div>`;

function calculator(page) {
  return `<div class="workspace" id="calculator"><div class="workspace-heading"><h2>Tank dimensions</h2><span class="local-label">Calculated in your browser</span></div><div class="tool-grid"><form class="input-side" id="tank-form" novalidate data-shape="${page.shape}" data-fixed="${Boolean(page.slug)}">
  ${!page.slug ? `<fieldset><legend>Tank shape</legend><div class="shape-options">${[['vertical', 'Vertical cylinder'], ['horizontal', 'Horizontal cylinder'], ['rectangular', 'Rectangular']].map(([shape, label]) => `<div class="shape-option"><input type="radio" id="shape-${shape}" name="shape" value="${shape}" ${shape === page.shape ? 'checked' : ''}><label for="shape-${shape}"><img src="assets/${shape}.svg" alt="" width="42" height="25">${label}</label></div>`).join('')}</div></fieldset>` : `<input type="hidden" name="shape" value="${page.shape}">`}
  <div class="unit-row"><label for="unit">Measurement unit</label><select name="unit" id="unit"><option value="mm">Millimeters (mm)</option><option value="cm">Centimeters (cm)</option><option value="m" selected>Meters (m)</option><option value="in">Inches (in)</option><option value="ft">Feet (ft)</option></select></div>
  <div class="dimensions">${field('diameter', 'Inside diameter', '1')}${field('length', 'Inside length', '2')}${field('width', 'Inside width', '1')}${field('height', 'Inside height', page.shape === 'rectangular' ? '0.5' : '2')}</div>
  <div class="field fill-field"><label for="fill">Liquid depth <span class="optional">(optional)</span></label><div class="input-wrap"><input type="number" id="fill" name="fill" step="any" inputmode="decimal" placeholder="Capacity only" value="${page.shape === 'horizontal' ? '0.5' : page.shape === 'rectangular' ? '0.3' : '1'}" aria-describedby="fill-hint error"><span class="unit-suffix">m</span></div><p class="hint" id="fill-hint">Measured vertically from the inside bottom. Blank = capacity only.</p></div>
  <p class="error" id="error" role="alert" hidden></p><div class="actions"><button class="primary" type="submit">Calculate volume</button>${icon('reset', 'Reset dimensions', 'reset')}</div></form>
  <section class="result-side" aria-label="Calculation results"><div class="result-top"><h3>FULL TANK CAPACITY</h3>${icon('copy', 'Copy results', 'copy', 'disabled')}</div><div id="result-output"><p class="result-number" id="total-liters">&mdash; <span>L</span></p><p class="result-secondary" id="total-gallons">Enter dimensions to calculate</p>
  <svg class="diagram" id="tank-diagram" viewBox="0 0 380 175" role="img" aria-labelledby="diagram-title"><title id="diagram-title">Tank measurement diagram</title></svg>
  <table class="result-table"><caption class="sr-only">Total capacity in other units</caption><tbody><tr><td>Imperial gallons</td><td id="imperial">&mdash;</td></tr><tr><td>Cubic meters</td><td id="meters">&mdash;</td></tr><tr><td>Cubic feet</td><td id="feet">&mdash;</td></tr></tbody></table>
  <div id="partial-results" hidden><div class="fill-results"><div class="metric"><small>Liquid volume</small><strong id="filled">&mdash;</strong><span id="filled-gallons"></span></div><div class="metric"><small>Remaining capacity</small><strong id="remaining">&mdash;</strong><span id="remaining-gallons"></span></div></div><div class="fill-bar"><span id="fill-bar"></span></div><p class="percent-label" id="percent"></p></div><p class="empty-note" id="capacity-only">Add a liquid depth to calculate current volume.</p></div></section></div><p class="tool-note">Inside dimensions &middot; Ideal geometry &middot; Flat-ended cylinders and rectangular tanks only</p></div><p class="status" id="status" role="status" aria-live="polite"></p><noscript><p>Enable JavaScript for interactive calculations. The formulas and examples below remain available without it.</p></noscript>`;
}

for (const page of pages) {
  const relative = page.slug ? '../' : './';
  const targets = { home: relative, horizontal: `${relative}horizontal-cylinder-tank-calculator/`, rectangular: `${relative}rectangular-tank-calculator/` };
  const content = html => html.replace(/\{\{(home|horizontal|rectangular)\}\}/g, (_, key) => targets[key]);
  const nav = pages.map(p => `<a href="${relative}${p.slug}" ${p === page ? 'aria-current="page"' : ''}>${p.nav}</a>`).join('');
  const canonical = url(page.slug);
  const schema = [
    { '@context': 'https://schema.org', '@type': 'WebSite', '@id': `${url('')}#website`, name: config.name, url: url(''), inLanguage: 'en-US' },
    { '@context': 'https://schema.org', '@type': 'WebApplication', name: page.heading, url: canonical, description: page.description, applicationCategory: 'UtilitiesApplication', operatingSystem: 'Any', browserRequirements: 'Requires JavaScript', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' } }
  ];
  if (page.slug) schema.push({ '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: url('') }, { '@type': 'ListItem', position: 2, name: page.heading, item: canonical }] });
  const dip = page.shape === 'horizontal' ? `<section id="dip-chart"><div class="dip-heading"><h2>Tank Dip Chart</h2>${icon('download', 'Download dip chart as CSV', 'download', 'disabled')}</div><p>Calculated at 10% increments of the inside diameter. This geometric table is not a certified tank calibration chart.</p><div class="table-scroll"><table class="dip-table"><caption class="sr-only">Liquid depth and corresponding volume</caption><thead><tr><th scope="col" id="depth-header">Depth (m)</th><th scope="col">Liters</th><th scope="col">US gallons</th><th scope="col">% full</th></tr></thead><tbody id="dip-body"><tr><td colspan="4">Enter valid dimensions to generate a chart.</td></tr></tbody></table></div></section>` : '';
  let html = `<!doctype html><html lang="en-US"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(page.title)}</title><meta name="description" content="${esc(page.description)}"><link rel="canonical" href="${esc(canonical)}"><meta name="robots" content="${preview ? 'noindex, nofollow' : 'index, follow'}"><meta name="theme-color" content="#087568"><meta property="og:type" content="website"><meta property="og:site_name" content="Tank Volume Lab"><meta property="og:title" content="${esc(page.title)}"><meta property="og:description" content="${esc(page.description)}"><meta property="og:url" content="${esc(canonical)}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${esc(page.title)}"><meta name="twitter:description" content="${esc(page.description)}">${config.verificationToken ? `<meta name="google-site-verification" content="${esc(config.verificationToken)}">` : ''}<link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/styles.css"><script type="application/ld+json">${JSON.stringify(schema).replaceAll('<', '\\u003c')}</script><script type="module" src="assets/app.js"></script></head>
  <body><a class="skip" href="#main">Skip to calculator</a><header class="site-header"><div class="wrap header-inner"><a class="brand" href="${relative}"><img src="assets/favicon.svg" alt="" width="34" height="34"><span>Tank Volume Lab<small>Free volume &amp; capacity calculators</small></span></a><nav aria-label="Main navigation">${nav}</nav></div></header><main id="main" class="wrap"><div class="intro">${page.slug ? `<div class="crumbs"><a href="${relative}">Home</a> / ${page.nav}</div>` : '<p class="eyebrow">Measure. Calculate. Know your capacity.</p>'}<h1>${page.heading}</h1><p>${page.intro}</p></div>${calculator(page)}<div class="below"><article class="article">${dip}${page.sections.map(([id, heading, body]) => `<section id="${id}"><h2>${heading}</h2>${content(body)}</section>`).join('')}<section id="faq"><h2>Frequently Asked Questions</h2>${page.faqs.map(([q, a]) => `<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</section><section id="methodology"><h2>Methodology &amp; Limitations</h2><p>Tank Volume Lab calculates ideal geometry in cubic meters, then converts the result using fixed unit definitions. Cylinders use circular area; horizontal partial fills use circular-segment area. Rectangular tanks use base area times height. See <a href="https://mathworld.wolfram.com/CircularSegment.html">the circular-segment formula</a> and <a href="https://www.nist.gov/pml/special-publication-811/nist-guide-si-appendix-b-conversion-factors/nist-guide-si-appendix-b8">NIST unit conversion guidance</a>.</p><p>Results are estimates based on ideal internal geometry. Real usable capacity can differ because of wall thickness, tank fittings, baffles, dished ends, freeboard and calibration requirements. These estimates do not replace certified measurement for industrial, safety or financial purposes.</p></section></article><aside class="aside"><h2>On this page</h2><a href="#calculator">Calculate tank volume</a>${page.shape === 'horizontal' ? '<a href="#dip-chart">Tank dip chart</a>' : ''}${page.sections.map(([id, heading]) => `<a href="#${id}">${heading}</a>`).join('')}<a href="#faq">Frequently asked questions</a><a href="#methodology">Methodology &amp; limitations</a><p>Measure the inside.<br>Small measurement differences can have a noticeable effect on volume.</p></aside></div></main><footer class="site-footer"><div class="wrap"><div class="footer-top"><strong>Tank Volume Lab</strong><div class="footer-links">${nav}</div></div><p class="footer-note" id="privacy">Privacy: entered dimensions are processed in your browser and are not sent to a backend. No accounts, analytics or tracking cookies are used. When deployed on GitHub Pages, GitHub may process basic connection information to provide hosting.</p></div></footer></body></html>`;
  if (page.slug) html = html.replaceAll('src="assets/', 'src="../assets/').replaceAll('href="assets/', 'href="../assets/');
  const directory = join(out, page.slug);
  await mkdir(directory, { recursive: true });
  await writeFile(join(directory, 'index.html'), html);
}
await writeFile(join(out, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(p => `<url><loc>${esc(url(p.slug))}</loc></url>`).join('')}</urlset>\n`);
await writeFile(join(out, 'robots.txt'), `# Robots rules apply only when this file is at the host root.\nUser-agent: *\n${preview ? 'Disallow: /' : 'Allow: /'}\nSitemap: ${url('sitemap.xml')}\n`);
await writeFile(join(out, '.nojekyll'), '');
await writeFile(join(out, '404.html'), `<!doctype html><html lang="en-US"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex"><title>Page not found - Tank Volume Lab</title></head><body><h1>Page not found</h1><p><a href="${esc(base.pathname)}">Return to Tank Volume Lab</a></p></body></html>`);
console.log(`${preview ? 'Local preview (noindex)' : 'Production'} build: ${out}\nBase URL: ${base.href}\n3 calculator pages generated. Supporting SEO targets remain provisional.`);
